### ISSUE TITLE
Error downloading com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.13.10:1.4.9

### ISSUE THREAD

**Issue by DiegoJohnsonL** [scapegoat-scala/sbt-scapegoat#148]
I've followed the repo's instructions to run scapegoat but I've being facing the next error

```
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.13.10:1.4.9
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\pc\.ivy2\localcom.sksamuel.scapegoat\scalac-scapegoat-plugin_2.13.10\1.4.9\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/sksamuel/scapegoat/scalac-scapegoat-plugin_2.13.10/1.4.9/scalac-scapegoat-plugin_2.13.10-1.4.9.pom
[error]   not found: https://repo.typesafe.com/typesafe/releases/com/sksamuel/scapegoat/scalac-scapegoat-plugin_2.13.10/1.4.9/scalac-scapegoat-plugin_2.13.10-1.4.9.pom
```

I've tried settings different versions for the plugging and scala version without any success. One thing i did realized is that even if i changed the version on my plugins.sbt and scala version the error keeps showing the same version as default and not the ones i specify. 

sbt.version = 1.5.0

My plugings.sbt file:

```
logLevel := Level.Warn

resolvers += "Typesafe repository" at "https://repo.typesafe.com/typesafe/releases/"

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.16")

//Tets coverage with jacoco
addSbtPlugin("com.github.sbt" % "sbt-jacoco" % "3.4.0")

addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.1.1")
```

build.sbt (scapegoatVersion in ThisBuild := "1.4.9"( shows red as if not recognized)

```
lazy val `tambo` = (project in file("."))
  .enablePlugins(PlayService, PlayScala, PlayLayoutPlugin, Common, JavaServerAppPackaging, UniversalDeployPlugin)
  .settings(
    name := "tambo",
    scalaVersion := "2.13.6",
    libraryDependencies ++= Seq(
      guice,
      ws,
      "org.joda" % "joda-convert" % "2.2.1",
      "net.logstash.logback" % "logstash-logback-encoder" % "6.2",
      "io.lemonlabs" %% "scala-uri" % "1.5.1",
      "net.codingwell" %% "scala-guice" % "4.2.6",
      "org.reactivemongo" %% "play2-reactivemongo" % "1.0.1-play28",
      "com.github.jwt-scala" %% "jwt-play" % "9.0.4",
      "com.stripe" % "stripe-java" % "20.131.0",
      //testing
      "org.scalatestplus.play" %% "scalatestplus-play" % "5.1.0" % Test,
      "org.scalatestplus" %% "mockito-3-4" % "3.2.10.0" % Test
    ),
    scalacOptions ++= Seq(
      "-feature",
      "-deprecation",
      "-Xfatal-warnings"
    ),
    publishTo := Some(("Artifactory Realm" at "http://68.61.211.197:8081/artifactory/sbt-release").withAllowInsecureProtocol(true)),
    credentials += Credentials("Artifactory Realm", "68.61.211.197", "admin", "Hamilton1!@#$%"),
    Universal / packageName := s"${name.value}",
    scapegoatVersion in ThisBuild := "1.4.9"
  )

libraryDependencies ++= Seq(jdbc, ehcache, ws, specs2 % Test, guice)
play.sbt.routes.RoutesKeys.routesImport += "play.modules.reactivemongo.PathBindables._"
routesGenerator := InjectedRoutesGenerator
```

**Comment by benco33** [comment]
I'm having the same issue. Did you figure it out or get any help @DiegoJohnsonL?

**Comment by mohika-knoldus** [comment]
I tried changing the version from 1.4.9 to  2.1.1 for scala-version 2.13.10. but the problem persists.

**Comment by Johnnei** [comment]
> I tried changing the version from 1.4.9 to 2.1.1 for scala-version 2.13.10. but the problem persists.

Please be sure to use the `ThisBuild / scapegoatVersion := "2.1.1"`
The current version of the sbt plugin isn't all that flexible in how to configure the version of scapegoat.

**Comment by mohika-knoldus** [comment]
If i try to use this, it isn't able to detect scapegoat , an error is thrown.

**Comment by Johnnei** [comment]
Could you share that log?

**Comment by mohika-knoldus** [comment]
Cannot resolve symbol scapegoatVersion
Cannot resolve symbol :=


[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.sksamuel.scapegoat:sbt-scapegoat:2.1.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.sksamuel.scapegoat:sbt-scapegoat;sbtVersion=1.0;scalaVersion=2.12:2.1.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/sksamuel/scapegoat/sbt-scapegoat_2.12_1.0/2.1.1/sbt-scapegoat-2.1.1.pom
[error]   not found: /home/knoldus/.ivy2/localcom.sksamuel.scapegoat/sbt-scapegoat/scala_2.12/sbt_1.0/2.1.1/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.sksamuel.scapegoat/sbt-scapegoat/scala_2.12/sbt_1.0/2.1.1/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.sksamuel.scapegoat/sbt-scapegoat/scala_2.12/sbt_1.0/2.1.1/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)

**Comment by Johnnei** [comment]
Ah, the version numbers of the sbt plugin and scapegoat aren't aligned. They have their own releases.

For the plugin you still need version `1.1.1` (usually in plugins.sbt) and with the snippet I shared above (in your build.sbt) it will choose the "actual" scapegoat version.

**Comment by mohika-knoldus** [comment]
[info] Defining Global / sbtStructureOptions, Global / sbtStructureOutputFile and 1 others.
[info] The new values will be used by cleanKeepGlobs
[info] 	Run `last` for details.
[info] Reapplying settings...
[info] set current project to Scala-KUP-Assessment (in build file:/home/knoldus/Desktop/Scala-KUP-Assessment/)
[info] Applying State transformations org.jetbrains.sbt.CreateTasks from /home/knoldus/.local/share/JetBrains/IdeaIC2023.2/Scala/repo/org/jetbrains/scala/sbt-structure-extractor_2.12_1.0/2023.1.0/sbt-structure-extractor-2023.1.0.jar
[info] Reapplying settings...
[info] set current project to Scala-KUP-Assessment (in build file:/home/knoldus/Desktop/Scala-KUP-Assessment/)
[warn] sbt 0.13 shell syntax is deprecated; use slash syntax instead: Global / dumpStructure
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] stack trace is suppressed; run 'last update' for the full output
[error] stack trace is suppressed; run 'last ModuleOne / update' for the full output
[error] stack trace is suppressed; run 'last ModuleTwo / update' for the full output
[error] stack trace is suppressed; run 'last ssExtractDependencies' for the full output
[error] stack trace is suppressed; run 'last ModuleOne / ssExtractDependencies' for the full output
[error] stack trace is suppressed; run 'last ModuleTwo / ssExtractDependencies' for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.13:1.0.0
[error]   Not found
[error]   Not found
[error]   not found: /home/knoldus/.ivy2/localcom.sksamuel.scapegoat/scalac-scapegoat-plugin_2.13/1.0.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/sksamuel/scapegoat/scalac-scapegoat-plugin_2.13/1.0.0/scalac-scapegoat-plugin_2.13-1.0.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/maven-releases/com/sksamuel/scapegoat/scalac-scapegoat-plugin_2.13/1.0.0/scalac-scapegoat-plugin_2.13-1.0.0.pom
[error] (ModuleOne / update) sbt.librarymanagement.ResolveException: Error downloading com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.13:1.0.0
[error]   Not found

addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.1.1")

this is what you meant???

**Comment by Johnnei** [comment]
Yes, but also add `ThisBuild / scapegoatVersion := "2.1.1"` to your root build.sbt.

**Comment by mohika-knoldus** [comment]
Yes, the problem is it cannot resolve the scapegoatVersion and this line of code in  build.sbt shows an error.

**Comment by Johnnei** [comment]
In the earlier log with the cannot resolve symbol errors, it was actually failing to find them because it couldn't download sbt-scapegoat:2.1.1

> Cannot resolve symbol scapegoatVersion
Cannot resolve symbol :=
> 
> [warn] Note: Some unresolved dependencies have extra attributes. Check that these dependencies exist with the requested attributes.
[warn] com.sksamuel.scapegoat:sbt-scapegoat:2.1.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn] Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.sksamuel.scapegoat:sbt-scapegoat;sbtVersion=1.0;scalaVersion=2.12:2.1.1
[error] Not found
[error] Not found

Key line being:
> Error downloading com.sksamuel.scapegoat:sbt-scapegoat;sbtVersion=1.0;scalaVersion=2.12:2.1.1

Now that you've fixed the ` addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.1.1")` in `plugins.sbt` the error is back too the scapegoat-compiler-plugin not being found.

> [error] not found: https://repo1.maven.org/maven2/com/sksamuel/scapegoat/scalac-scapegoat-plugin_2.13/1.0.0/scalac-scapegoat-plugin_2.13-1.0.0.pom

The default version in sbt-scapegoat is still scapegoat 1.0.0 which it tries to download, but can't because it's not released for that scala version. But now that plugin is loaded correctly adding `ThisBuild / scapegoatVersion := "2.1.1"` again in your root `build.sbt` (not plugins.sbt !) it should find the symbols and change to pick `scalac-scapegoat-plugin_2.13.10-2.1.1`.

**Comment by mohika-knoldus** [comment]
Yes i have tried doing that, and yes ofcourse ThisBuild / scapegoatVersion := "2.1.1" is mentioned in buil.sbt file and not in plugins.sbt. it is still unable to find it.

**Comment by mohika-knoldus** [comment]
I tried to build with an error in my code and then it read the version from build.sbt file and error is gone. Thank you for helping me this far. Saves BigTime.
