### ISSUE TITLE
Unable to integrate the plugin in a multimodule project. version - 1.1.1 and scala version- 2.13.10 sbt- 1.8.3 

### ISSUE THREAD

**Issue by mohika-knoldus** [scapegoat-scala/sbt-scapegoat#156]
Reapplying settings...
[info] set current project to Scala-KUP-Assessment (in build file:/home/knoldus/Desktop/Scala-KUP-Assessment/)
[warn] sbt 0.13 shell syntax is deprecated; use slash syntax instead: Global / dumpStructure
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] stack trace is suppressed; run 'last update' for the full output
[error] stack trace is suppressed; run 'last ModuleOne / update' for the full output
[error] stack trace is suppressed; run 'last ModuleTwo / update' for the full output
[error] stack trace is suppressed; run 'last ssExtractDependencies' for the full output
[error] stack trace is suppressed; run 'last ModuleOne / ssExtractDependencies' for the full output
[error] stack trace is suppressed; run 'last ModuleTwo / ssExtractDependencies' for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.13:1.0.0
[error]   Not found
[error]   Not found
[error]   not found: /home/knoldus/.ivy2/localcom.sksamuel.scapegoat/scalac-scapegoat-plugin_2.13/1.0.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/sksamuel/scapegoat/scalac-scapegoat-plugin_2.13/1.0.0/scalac-scapegoat-plugin_2.13-1.0.0.pom
[error] (ModuleOne / update) sbt.librarymanagement.ResolveException: Error downloading com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.13:1.0.0
[error]   Not found
[error]   Not found

Build.sbt:- 
ThisBuild / version := "0.1.0-SNAPSHOT"

ThisBuild / scalaVersion := "2.13.10"

ThisBuild / coverageEnabled := true

enablePlugins(ScoverageSbtPlugin)

lazy val root = (project in file("."))
  .settings(
    name := "Scala-KUP-Assessment"
  ).aggregate(ModuleOne, ModuleTwo)

lazy val ModuleOne = project.in(file("ModuleOne"))
  .settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % "3.2.15" % Test
    )
  ).enablePlugins(ScoverageSbtPlugin)

lazy val ModuleTwo = project.in(file("ModuleTwo"))
  .settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % "3.2.15" % Test,
      "io.jvm.uuid" %% "scala-uuid" % "0.3.1",
      "org.scalatestplus" %% "mockito-3-4" % "3.2.10.0" % Test,
      "com.typesafe.scala-logging" %% "scala-logging" % "3.9.5",
      "ch.qos.logback" % "logback-classic" % "1.3.5"
    )
  ).enablePlugins(ScoverageSbtPlugin)

**Comment by Johnnei** [comment]
Should be similar to #148

**Comment by mohika-knoldus** [comment]
Thanks @Johnnei for resolving this through #148 .
