### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by sebarys** [scapegoat-scala/sbt-scapegoat#181]
Hi,

Is there a plan to support Scala 3?

I've just checked https://docs.scala-lang.org/scala3/guides/migration/scala3-migrate.html dependency update and scapegoat plugin is blocking migration in my case:

```
[error]
[error] Incompatible Libraries:
[error] ("com.sksamuel.scapegoat" %% "scalac-scapegoat-plugin" % "2.1.6" % "scapegoat").cross(CrossVersion.full) (Full cross-version)
```

**Comment by Johnnei** [comment]
As far I'm aware the sbt plugin isn't the blocker here. It's the actual compiler plugin. You can track progress on this issue: https://github.com/scapegoat-scala/scapegoat/issues/521
