### ISSUE TITLE
Can't use plugin with sbt 1.0

### ISSUE THREAD

**Issue by unoexperto** [scapegoat-scala/sbt-scapegoat#56]
Not sure what I do wrong but plugin is not available neither with version 1.0.0 nor with 1.0.1

```
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.sksamuel.scapegoat:sbt-scapegoat:1.0.4 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.sksamuel.scapegoat:sbt-scapegoat:1.0.4 (scalaVersion=2.12, sbtVersion=1.0) (/home/expert/work/sideprojects/akka-http-throttling/project/plugins.sbt#L5-6)
[warn] 		  +- default:akka-http-throttling-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)

```

What am I missing ?

**Comment by pomadchin** [comment]
Specify the latest scapegoat version to be added as a dep by this plugin [docs](https://github.com/sksamuel/sbt-scapegoat#how-to-use): 

```scala
scapegoatVersion in ThisBuild := "1.3.3"
```

[Maven central link to find the latest scapegoat version](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.sksamuel.scapegoat%22%20AND%20a%3A%22scalac-scapegoat-plugin_2.12%22)

**Comment by ashleymercer** [comment]
I've just hit this same problem: the main documentation simply says to set `scapegoatVersion`, but (at least for multi-module builds) it's necessary to explicitly set `scapegoatVersion in ThisBuild`.

Two questions:

- could the documentation be updated accordingly, please?
- why is it necessary to explicitly specify `in ThisBuild`? I'm not an sbt expert, but other configuration settings don't require this

**Comment by DWvanGeest** [comment]
Setting `scapegoatVersion in ThisBuild := "1.3.3"` in `build.sbt` doesn't even seem to help for me, in a multi-module build for SBT `0.13.15`.

**Comment by susu** [comment]
Thanks! This `in ThisBuild` helped me for scala ``2.12`` and SBT ``1.0.3`` in case of multi-project build. I had to define it for all subproject - i.e. in common place.
