### ISSUE TITLE
 Unresolved dependencies path:

### ISSUE THREAD

**Issue by QADEvops1** [scapegoat-scala/sbt-scapegoat#77]
Hello,

I am trying out this plugin and facing some issues.  I am not very familiar with SBT, scala.  I have a sample project and I am getting "Unresolved dependencies path:" error.  I checked out different issues mentioned here and I am not able to fix this issue.

I really appreciate any help.  Thanks in advance.
Project sctrucure
![image](https://user-images.githubusercontent.com/36966485/41683965-27440342-74aa-11e8-9182-512a3cc594f2.png)
build.sbt
name := "sbt-scoverage-samples"

organization := "org.scoverage"

version := "1.5.1"

scalaVersion := "2.12.3"

crossScalaVersions := Seq("2.11.11", "2.12.3")

javacOptions ++= Seq("-source", "1.6", "-target", "1.6")

scalacOptions ++= Seq("-unchecked", "-deprecation", "-feature")

scalacOptions in (Compile, doc) ++= Seq("-unchecked", "-deprecation", "-diagrams", "-implicits", "-skip-packages", "samples")

libraryDependencies ++= Seq(
  "commons-io"                 %  "commons-io"             % "2.4",
  "com.typesafe.akka"          %% "akka-actor"             % "2.4.16",
  "com.typesafe.akka"          %% "akka-testkit"           % "2.4.16"           % "test",
  "org.typelevel"              %% "macro-compat"           % "1.1.1",
  "org.scala-lang"             %  "scala-reflect"          % scalaVersion.value % "provided",
  "org.scalatest"              %% "scalatest"              % "3.0.0"            % "test",
  "com.sksamuel.scapegoat"     %  "sbt-scapegoat"          % "1.0.9",
   compilerPlugin("org.scalamacros" %% "paradise" % "2.1.0" cross CrossVersion.full)
)

coverageMinimum := 70

coverageFailOnMinimum := false

coverageHighlighting := true

publishArtifact in Test := false

parallelExecution in Test := false

scapegoatVersion in ThisBuild := "1.0.9"

plugins.sbt inside project folder

addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")

addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.0.9")

build file inside project folder
sbt.version=1.1.6
scapegoatVersion in ThisBuild := "1.0.9"

When I run this one

[info] Loading settings from plugins.sbt ...
[info] Loading project definition from C:\SonarQube\sonar-scanner-3.0.3.778-windows\bin\New folder\New folder\sbt-scoverage-samples-master\project
[info] Loading settings from build.sbt ...
[info] Set current project to sbt-scoverage-samples (in build file:/C:/SonarQube/sonar-scanner-3.0.3.778-windows/bin/New%20folder/New%20folder/sbt-scoverage-samples-master/)
[info] sbt server started at local:sbt-server-152f935d2a5fe3319b75
sbt:sbt-scoverage-samples> scapegoat
[info] [scapegoat] Removing scapegoat class directory: C:\SonarQube\sonar-scanner-3.0.3.778-windows\bin\New folder\New folder\sbt-scoverage-samples-master\target\scala-2.12\sc
apegoat-classes
[info] Updating ...
[warn]  module not found: com.sksamuel.scapegoat#sbt-scapegoat;1.0.9
[warn] ==== local: tried
[warn]   C:\Users\.ivy2\local\com.sksamuel.scapegoat\sbt-scapegoat\1.0.9\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/sksamuel/scapegoat/sbt-scapegoat/1.0.9/sbt-scapegoat-1.0.9.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\.sbt\preloaded\com.sksamuel.scapegoat\sbt-scapegoat\1.0.9\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/.sbt/preloaded/com/sksamuel/scapegoat/sbt-scapegoat/1.0.9/sbt-scapegoat-1.0.9.pom
[warn]  module not found: com.sksamuel.scapegoat#scalac-scapegoat-plugin_2.12;1.0.9
[warn] ==== local: tried
[warn]   C:\Users\.ivy2\local\com.sksamuel.scapegoat\scalac-scapegoat-plugin_2.12\1.0.9\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/sksamuel/scapegoat/scalac-scapegoat-plugin_2.12/1.0.9/scalac-scapegoat-plugin_2.12-1.0.9.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\.sbt\preloaded\com.sksamuel.scapegoat\scalac-scapegoat-plugin_2.12\1.0.9\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/.sbt/preloaded/com/sksamuel/scapegoat/scalac-scapegoat-plugin_2.12/1.0.9/scalac-scapegoat-plugin_2.12-1.0.9.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.sksamuel.scapegoat#sbt-scapegoat;1.0.9: not found
[warn]  :: com.sksamuel.scapegoat#scalac-scapegoat-plugin_2.12;1.0.9: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.sksamuel.scapegoat:sbt-scapegoat:1.0.9 (C:\SonarQube\sonar-scanner-3.0.3.778-windows\bin\New folder\New folder\sbt-scoverage-samples-master\build.sbt#L17-2
7)
[warn]            +- org.scoverage:sbt-scoverage-samples_2.12:1.5.1
[warn]          com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.12:1.0.9 ((com.sksamuel.scapegoat.sbt.ScapegoatSbtPlugin.projectSettings) ScapegoatSbtPlugin.scala#L108)
[warn]            +- org.scoverage:sbt-scoverage-samples_2.12:1.5.1
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.sksamuel.scapegoat#sbt-scapegoat;1.0.9: not found
[error] unresolved dependency: com.sksamuel.scapegoat#scalac-scapegoat-plugin_2.12;1.0.9: not found
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2398)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:272)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.lang.Thread.run(Unknown Source)
sbt:sbt-scoverage-samples> [error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.sksamuel.scapegoat#sbt-scapegoat;1.0.9: not found
[error] unresolved dependency: com.sksamuel.scapegoat#scalac-scapegoat-plugin_2.12;1.0.9: not found
[error] Total time: 2 s, completed Jun 20, 2018 4:47:24 PM

Thanks

**Comment by BalmungSan** [comment]
Hello @QADEvops1,
The main problem is that you're adding this plugin as a dependency of the project.

```scala
libraryDependencies ++= Seq(
"commons-io" % "commons-io" % "2.4",
"com.typesafe.akka" %% "akka-actor" % "2.4.16",
"com.typesafe.akka" %% "akka-testkit" % "2.4.16" % "test",
"org.typelevel" %% "macro-compat" % "1.1.1",
"org.scala-lang" % "scala-reflect" % scalaVersion.value % "provided",
"org.scalatest" %% "scalatest" % "3.0.0" % "test",
"com.sksamuel.scapegoat" % "sbt-scapegoat" % "1.0.9", // this line should be removed
compilerPlugin("org.scalamacros" %% "paradise" % "2.1.0" cross CrossVersion.full)
)
```

That's not only unnecessary but, probably, is the one that is failing. Adding the plugin in the _project/plugins.sbt_ file is enough.

Also, if you're using `Scala 2.12` [you need **Java 8**](https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html#dropping-old-jvms).

**Comment by BalmungSan** [comment]
Hello @QADEvops1,
I'm sorry, I didn't noticed another silly mistake.

You're trying to use scapegoat `1.0.9` which does not exist. This maybe confusing as in the releases page of this project you will find version `1.0.9` and I, in my previous comment, use `1.0.9`.
That's because, This is the **SBT** plugin which does have a version `1.0.9`. But this plugins serves as a wrapper around the real [**scalac** scapegoat plugin](https://github.com/sksamuel/scapegoat), which is the one that does the analysis. And if you search in that page you will find there is no `1.0.9` version - the latest one is `1.3.5`.

So, to fix this, you only need to change this line, in your _"build.sbt"_ file.
```scala
scapegoatVersion in ThisBuild := "1.0.9" // bad one
scapegoatVersion in ThisBuild := "1.3.5" // good one (or any other version).
```

Also, you have a similar line in your  _"project/build.sbt"_ file, that one is unnecessary.
Also, you should move the following line to the file  _"project/build.properties"_ - That's the standard location.
```scala
sbt.version=1.1.6
```
Hope I made myself clear :+1: 😄

**Comment by QADEvops1** [comment]
Thanks for the response @BalmungSan 

I updated the build.sbt
scapegoatVersion in ThisBuild := "1.3.5"

also removed this line from project/build.sbt file.  project/build.properties has this sbt.version=1.1.6

project/plugins.sbt I have not added this one "addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.0.4")"

Output:
C:\SonarQube\sonar-scanner-3.0.3.778-windows\bin\New folder\New folder\sbt-scoverage-samples-master\build.sbt:37: error: not found: value scapegoatVersion
scapegoatVersion in ThisBuild := "1.3.5"
^

When I add the plugin details in project/plugins.sbt as 
 addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.0.4")

Output:
[warn]  module not found: com.sksamuel.scapegoat#sbt-scapegoat;1.0.4
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.sksamuel.scapegoat/sbt-scapegoat/scala_2.12/sbt_1.0/1.0.4/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.sksamuel.scapegoat/sbt-scapegoat/scala_2.12/sbt_1.0/1.0.4/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\.ivy2\local\com.sksamuel.scapegoat\sbt-scapegoat\scala_2.12\sbt_1.0\1.0.4\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/sksamuel/scapegoat/sbt-scapegoat_2.12_1.0/1.0.4/sbt-scapegoat-1.0.4.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\.sbt\preloaded\com.sksamuel.scapegoat\sbt-scapegoat\1.0.4\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/.sbt/preloaded/com/sksamuel/scapegoat/sbt-scapegoat_2.12_1.0/1.0.4/sbt-scapegoat-1.0.4.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.sksamuel.scapegoat#sbt-scapegoat;1.0.4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.sksamuel.scapegoat:sbt-scapegoat:1.0.4 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.sksamuel.scapegoat:sbt-scapegoat:1.0.4 (scalaVersion=2.12, sbtVersion=1.0) (C:\SonarQube\sonar-scanner-3.0.3.778-windows\bin\New folder\New fold
erage-samples-master\project\plugins.sbt#L3-4)
[warn]            +- default:sbt-scoverage-samples-master-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.sksamuel.scapegoat#sbt-scapegoat;1.0.4: not found
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2398)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:272)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.lang.Thread.run(Unknown Source)
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? [error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.sksamuel.scapegoat

When I do this
project/plugins.sbt I have added this one "addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.3.5")"

[warn]  module not found: com.sksamuel.scapegoat#sbt-scapegoat;1.3.5
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.sksamuel.scapegoat/sbt-scapegoat/scala_2.12/sbt_1.0/1.3.5/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.sksamuel.scapegoat/sbt-scapegoat/scala_2.12/sbt_1.0/1.3.5/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\sira7003\.ivy2\local\com.sksamuel.scapegoat\sbt-scapegoat\scala_2.12\sbt_1.0\1.3.5\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/sksamuel/scapegoat/sbt-scapegoat_2.12_1.0/1.3.5/sbt-scapegoat-1.3.5.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\sira7003\.sbt\preloaded\com.sksamuel.scapegoat\sbt-scapegoat\1.3.5\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/sira7003/.sbt/preloaded/com/sksamuel/scapegoat/sbt-scapegoat_2.12_1.0/1.3.5/sbt-scapegoat-1.3.5.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.sksamuel.scapegoat#sbt-scapegoat;1.3.5: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.sksamuel.scapegoat:sbt-scapegoat:1.3.5 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.sksamuel.scapegoat:sbt-scapegoat:1.3.5 (scalaVersion=2.12, sbtVersion=1.0) (C:\SonarQube\sonar-scanner-3.0.3.778-windows\bin\New folder\New folder\sbt-scov
erage-samples-master\project\plugins.sbt#L3-4)
[warn]            +- default:sbt-scoverage-samples-master-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.sksamuel.scapegoat#sbt-scapegoat;1.3.5: not found
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2398)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:272)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.lang.Thread.run(Unknown Source)
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? [error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.sksamuel.scapegoat#sbt-scapeg
oat;1.3.5: not found

**Comment by BalmungSan** [comment]
Hi, I may be wrong, but I assume the `1.0.4` version of the **SBT** plugin is not available either for scala `2.12` or for sbt `1.0`.

If you use the `1.0.9` version it should work fine. _(I work in 3 projects with that setup and there is no problem)_.

If you, for some reason, need an older version. Then you need to check the version compatibilities. 

:wink:

**Comment by QADEvops1** [comment]
Thanks for the response @BalmungSan 

I have sbt version as sbt.version=1.1.6 in my project/build file.  But it is showing as (scalaVersion=2.12, sbtVersion=1.0)
Is this the problem?

**Comment by BalmungSan** [comment]
Hi,

More or less.

*SBT* recently _(like at the end of the last year)_ upgrade from version `0.13` to `1.0`.
That was a major breaking change, and all plugins had to be re-compiled and re-published for that version. 
The same happens for scala `2.11` and `2.12`.

sbt `1.1.6` needs a plugin avaliable for sbt `1.0`.

As I said in my previous comment, I belive the version `1.0.4` of this plugin _(the scapegoat sbt plugin)_ was not released either for sbt `1.0` or scala `2.12` - probably because those versions did exist at that time.

So the simplest way of fixing this issue is upgrading your scapegoat sbt plugin from `1.0.4` to `1.0.9` _(latest release)_ - in your _"project/plugins.sbt"_ file.

**Comment by aiya000** [comment]
It worked for me too :+1:

```project/build.properties
sbt.version=1.1.6
```

```project/plugins.sbt
...
addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.0.9")
```

```build.sbt
...

scapegoatVersion in ThisBuild := "1.3.5"
```

**Comment by aolins** [comment]
worked for me with 
addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.0.4")
scapegoatVersion in ThisBuild := "1.3.5"

**Comment by Johnnei** [comment]
#157 made the out of the box experience a lot nicer with regard to compatible version selection.
