### ISSUE TITLE
scapegoat broken

### ISSUE THREAD

**Issue by JohnReedLOL** [scapegoat-scala/sbt-scapegoat#82]
See: https://imgur.com/a/CHDp1q7

**Comment by BalmungSan** [comment]
Maybe this is a duplicate of #77 ?

**Comment by Johnnei** [comment]
Very likely yes. https://github.com/scapegoat-scala/sbt-scapegoat/pull/157 made the out of the box experience a lot nicer with regard to compatible version selection.
